### ISSUE TITLE
Custom Component not working (Angular 2.2.3)

### ISSUE THREAD

**Issue by trumbitta** [scttcper/ngx-toastr#91]
Trying to use a custom component as my toast (like the PinkToast example) I get:

`Error: Error in :0:0 caused by: Cannot read property 'optionsOverride' of undefined at ViewWrappedError.ZoneAwareError`

And it seems related to this line: https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toast-component.ts#L83

or this one: https://github.com/scttcper/ngx-toastr/blob/78bcd5f45c29137ea7c75f689a8962195b138f4f/src/lib/toastr-service.ts#L159

Any hints? :)

**Comment by scttcper** [comment]
Are you using AoT compilation? Inheritance only works with AoT. If you're using angular-cli add --aot to the serve command

**Comment by trumbitta** [comment]
Nope I'm not using AoT nor angular-cli :-/ I was hoping this would work a-la https://ng-bootstrap.github.io/#/components/modal

Any chances to see it working with a custom component as the toast body without AoT?

**Comment by scttcper** [comment]
I've taken another look at it. It looks like component inheritance is possible, but the constructor has to be copied from the toast component. Otherwise, it ends up with the error you were getting. I've released 4.4.0 to better assist with component inheritance and updated the pink component as an example of what worked for me. https://github.com/scttcper/ngx-toastr/blob/master/src/app/pink.toast.ts

**Comment by trumbitta** [comment]
Thanks! I'll take it for a spin right now!

**Comment by trumbitta** [comment]
Now even the simple "success" toast doesn't work, and I'm getting:

`Error: Error in ./TestToastComponent class TestToastComponent - inline template:2:0 caused by: this._appRef.attachView is not a function at ViewWrappedError.ZoneAwareError`

A quick search brought me here: http://stackoverflow.com/questions/42315480/angular-material-2-snackbar-doesnt-work

If this can only work with Angular 2.4, then I'm done. Can't update because the app is hybrid and I'm stuck at v2.2.3 until ui-router/ng1-to-ng2 gets updated (ref: https://github.com/ui-router/ng1-to-ng2/issues/26) :-/

**Comment by scttcper** [comment]
I had dropped support for 2.2 as angular/material did too. I've brought back the few lines I think are necessary for 2.2.x. Try ngx-toastr@4.4.1. 

As a warning, ngx-toastr 5.x will be out soon which will support Angular 4.x and will most likely drop support for 2.2 and 2.4.

**Comment by yarrgh** [comment]
@scttcper I'd suggest that when you release 5.x, that you move the 4.x code into a separate branch and only support major bug fixes (if any). That way those that can't migrate to Angular 4.x right away can stay pinned to ngx-toastr 4.x until they can upgrade to Angular 4.

**Comment by scttcper** [comment]
@yarrgh for sure, will do.

It looks like the only breaking change can be avoided for now. OpaqueToken is becoming something else eventually. And people need to bring that new @angular/animations library for 4.x. https://github.com/angular/angular/blob/master/CHANGELOG.md#deprecations-1

**Comment by trumbitta** [comment]
Everything's looking fine on my end, @scttcper . Thanks for your support!
