### ISSUE TITLE
Not working with Angular 8.1.1

### ISSUE THREAD

**Issue by rohanshenoy96** [scttcper/ngx-toastr#791]
```
ERROR in node_modules/ngx-toastr/portal/portal.d.ts(26,9): error TS1086: An accessor cannot
be declared in an ambient context.
    node_modules/ngx-toastr/toastr/toast-noanimation.component.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/ngx-toastr/toastr/toast.component.d.ts(26,9): error TS1086: An accessor cannot
be declared in an ambient context.
```

Problem in importing styles using scss and if you use angular.json to load the css then we get the above error

**Comment by wwarby** [comment]
Occurs on the latest version of 8x too (8.2.14). According to a similar issue with another library the issue is actually compability with the version of TypeScript but on Angular 8 you can't upgrade to TypeScript 3.7.x which is what is needed to resolve the issue (and I can't upgrade to Angular 9 because another plugin I use is incompatible). Rolling back from v12 to 11.2.1 solved the problem for now.

**Comment by scttcper** [comment]
This is covered in the readMe. Latest requires v9 https://github.com/scttcper/ngx-toastr#dependencies
