### ISSUE TITLE
Make properties with default values optional in `IndividualConfig` and `GlobalConfig`

### ISSUE THREAD

**Issue by mmmichl** [scttcper/ngx-toastr#316]
With the latest typescript (2.6), I am forced to define almost all properties on `IndividualConfig` and `GlobalConfig`, although I just might only want to change some values.

E.g.:
```TypeScript
this.toastrService.success('message', 'title', { timeOut: 1000 });
```

results in:
```
error TS2322: Type '{ timeOut: number; }' is not assignable to type 'IndividualConfig'.
  Property 'disableTimeOut' is missing in type '{ timeOut: number; }'.
```

I guess the fix should be easy (add question marks in the interface definitions), but is this OK to do so?

**Comment by yarrgh** [comment]
That is what `Partial<IndividualConfig>` and `Partial<GlobalConfig>` are supposed to do. Those are supposed to make the interfaces have all optional properties. I'd this not the case?

**Comment by yarrgh** [comment]
That is what `Partial<IndividualConfig>` and `Partial<GlobalConfig>` are supposed to do. Those are supposed to make the interfaces have all optional properties. I'd this not the case?

**Comment by yarrgh** [comment]
That is what `Partial<IndividualConfig>` and `Partial<GlobalConfig>` are supposed to do. Those are supposed to make the interfaces have all optional properties. I'd this not the case?

**Comment by mmmichl** [comment]
I actually tried it. But unfortunately this does not help if the method parameter is defined with the non-partial interface. Typescript ensures here, that all non optional properties must be set.

I also have to correct my ticket description: It seems that this type error appears, after I upgraded Angular 4 to 5. I downgraded Typescript from 2.6 to the version I used before, and the type error remained. An other reason could be, that I upgraded angular-cli. I will have a closer look tomorrow.

**Comment by yarrgh** [comment]
That's interesting, the Partial class is a TypeScript class. Unless they got rid of it in 2.6, it should work regardless of what version of TypeScript you have. 

I'll take a look into this later when I have time unless someone beats me to it

**Comment by mmmichl** [comment]
Oh, the partial assignment works.

```Typescript
const config: Partial<IndividualConfig> = {
  timeOut: 1000
}; // no compiler error

toastr.sccuess('message', 'title', config); // error
```
That's because the method is somewhere defined as follows:
```Typescript
success(message: string, title: string, config: IndividualConfig);
                                                ^- no Partial<...>, therefore the error
```

**Comment by yarrgh** [comment]
If you look at the source, that method doesn't accept the IndividualConfig interface directly. It accepts a `Partial<IndividualConfig>` as the override object. It shouldn't error.

**Comment by scttcper** [comment]
what version is installed?

**Comment by yarrgh** [comment]
If you were using version 6.4, the last version with Angular 4 support, that may be why you are running into issues, that was the last version before we switched to using partials.

I'm still confused because that is also when we switched the interfaces to not use optional properties (because we started using partials in the public API)
