### ISSUE TITLE
Getting  ambient context error after adding Toastr to my Angular Project

### ISSUE THREAD

**Issue by jawil003** [scttcper/ngx-toastr#787]
```
ERROR in node_modules/ngx-toastr/portal/portal.d.ts(26,9): error TS1086: 
An accessor cannot be declared in an ambient context.
    node_modules/ngx-toastr/toastr/toast.component.d.ts(26,9): error TS1086: 
An accessor cannot be declared in an ambient context.
    node_modules/ngx-toastr/toastr/toast-noanimation.component.d.ts(19,9): error TS1086: 
An accessor cannot be declared in an ambient context.
```

I added css and min.js of toastr and added the Modules like described in the Description. Anyone faced a similar Issue and can help me out?

**Comment by ShinRai1090** [comment]
Facing the similar issue. It used to work fine with 11.3.0 and angular 8, but with angular 9 its causing these errors :(

**Comment by jawil003** [comment]
And you switched back to Angular 8 and it is ok now?

**Comment by ShinRai1090** [comment]
> And you switched back to Angular 8 and it is ok now?

I installed version 11.3.3 (the one for Angular 8) and for now it seems to be working.
` npm i --save ngx-toastr@11.3.3 `

**Comment by scttcper** [comment]
What’s in package.json for you two?

**Comment by jawil003** [comment]
> 
> 
> What’s in package.json for you two?

For me these are my dependencies (in packkage.json):
```
"dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@rxweb/reactive-form-validators": "^1.9.7",
    "all": "^0.0.0",
    "bootstrap": "^4.4.1",
    "crypto-js": "^3.1.9-1",
    "install": "^0.13.0",
    "jquery": "^3.4.1",
    "lazysizes": "^5.2.0-beta1",
    "modernizr": "^3.8.0",
    "npm": "^6.13.6",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "typescript-logging": "^0.6.4",
    "zone.js": "~0.9.1"
  },
```

**Comment by scttcper** [comment]
You're using angular 8. 11.3.x is the last available version https://github.com/scttcper/ngx-toastr#dependencies
